-- Two-phase release bootstrap (mandatory for embedding xlang frontend runtime).
--
-- Comedy: you cannot embed .xlang runtime until something can compile it.
--   1) Build stage-1 `xlang` WITHOUT final runtime embed (bridges may already exist as .a).
--   2) Stage-1 compiles src/runtime/frontend → runtime.o / libruntime.a
--   3) Pack bridges into a single archive; xxd/bin2c → build/embed/embedded_*.c
--   4) Rebuild `xlang` from scratch WITH XLANG_HAS_EMBEDDED_* payloads.
--
-- Dev builds skip this: in-tree findLibrary + module paths.
--
-- Usage:
--   xmake --root=...          # normal stage-1/dev
--   xmake build_bridges_pack  # pack host bridge .a files
--   xmake bootstrap_embed     # after stage-1 exists: compile runtime + generate embeds
--   xmake -r xlang            # stage-2 rebuild picks up build/embed/*.c

local function bridge_names()
    return {"filesystem", "net", "tls", "process", "time", "panic", "thread"}
end

target("build_bridges_pack")
    set_kind("phony")
    set_default(false)
    on_build(function (target)
        import("core.project.project")
        local outdir = path.join(os.projectdir(), "build", "embed")
        os.mkdir(outdir)
        local members = {}
        for _, name in ipairs(bridge_names()) do
            local lib = path.join(os.projectdir(), "build", "lib" .. name .. ".a")
            if os.isfile(lib) then
                table.insert(members, lib)
            end
        end
        if #members == 0 then
            raise("no bridge libraries found under build/; build bridges first")
        end
        local packed = path.join(outdir, "bridges.a")
        -- Flatten: extract objects into a temp dir and re-archive (portable enough for bootstrap).
        local tmp = path.join(outdir, "bridge_objs")
        os.tryrm(tmp)
        os.mkdir(tmp)
        for _, lib in ipairs(members) do
            os.vrunv("ar", {"x", lib}, {curdir = tmp})
        end
        local objs = os.files(path.join(tmp, "*.o"))
        if #objs == 0 then
            -- macOS may use .o without path join glob; list dir
            for _, f in ipairs(os.filedirs(path.join(tmp, "*"))) do
                if f:endswith(".o") then
                    table.insert(objs, f)
                end
            end
        end
        os.tryrm(packed)
        local args = {"rcs", packed}
        for _, o in ipairs(objs) do
            table.insert(args, o)
        end
        os.vrunv("ar", args)
        print("packed bridges → " .. packed)
    end)

target("bootstrap_embed")
    set_kind("phony")
    set_default(false)
    add_deps("build_bridges_pack")
    on_build(function (target)
        local root = os.projectdir()
        local outdir = path.join(root, "build", "embed")
        os.mkdir(outdir)

        local xlang = path.join(root, "build", "xlang")
        if not os.isfile(xlang) then
            raise("stage-1 xlang not found at " .. xlang .. "; build xlang first")
        end

        local runtime_entry = path.join(root, "src", "runtime", "frontend", "runtime.xlang")
        if not os.isfile(runtime_entry) then
            -- Accept package directory layout
            runtime_entry = path.join(root, "src", "runtime", "frontend")
        end

        local runtime_o = path.join(outdir, "runtime.o")
        -- Compile frontend runtime to object with --no-bridge/--build=object as appropriate.
        os.vrunv(xlang, {
            "build", runtime_entry,
            "--build=object",
            "--no-bridge",
            "-o", runtime_o
        })

        local runtime_a = path.join(outdir, "runtime.a")
        os.tryrm(runtime_a)
        os.vrunv("ar", {"rcs", runtime_a, runtime_o})

        local bridges_a = path.join(outdir, "bridges.a")
        if not os.isfile(bridges_a) then
            raise("bridges.a missing; run build_bridges_pack")
        end

        -- Generate C payloads (xxd -i compatible).
        local function bin2c(infile, outfile, symbol)
            local data = io.readfile(infile, {encoding = "binary"})
            local f = io.open(outfile, "w")
            f:write("/* generated by bootstrap_embed — do not edit */\n")
            f:write("const unsigned char " .. symbol .. "[] = {\n")
            local bytes = {}
            for i = 1, #data do
                bytes[#bytes + 1] = string.format("0x%02x", data:byte(i))
                if i % 12 == 0 then
                    f:write("  " .. table.concat(bytes, ", ") .. ",\n")
                    bytes = {}
                end
            end
            if #bytes > 0 then
                f:write("  " .. table.concat(bytes, ", ") .. "\n")
            end
            f:write("};\n")
            f:write("const unsigned long " .. symbol .. "_size = " .. tostring(#data) .. ";\n")
            f:close()
            print("wrote " .. outfile)
        end

        bin2c(runtime_a, path.join(outdir, "embedded_runtime.c"), "xlang_embedded_runtime")
        bin2c(bridges_a, path.join(outdir, "embedded_bridges.c"), "xlang_embedded_bridges")
        print("bootstrap embed ready — rebuild xlang to pick up XLANG_HAS_EMBEDDED_*")
    end)
