#include "xlang/codegen.h"

#include "xlang/error.h"
#include "xlang/syscalls.h"

#include <sstream>

namespace xlang {

Codegen::Codegen(CodegenOptions options) : options_(std::move(options)) {}

CodegenResult Codegen::generate(const Program& program, const CodegenOptions& options) {
    Codegen cg(options);
    cg.collectSyscalls(program);
    cg.emitPrelude(program);
    cg.emitGlobals(program);
    cg.emitGlobalInit(program);
    for (const Function& function : program.functions) {
        if (function.syscall) {
            continue;
        }
        if (function.external) {
            cg.emitDeclareFunction(function);
        } else if (!function.body.statements.empty()) {
            cg.defined_functions_.insert(function.name);
            cg.emitFunction(function);
        }
    }
    cg.emitSyscallLowering();

    CodegenResult result;
    result.ir = std::move(cg.output_);
    result.syscalls = std::move(cg.syscalls_);
    result.needs_thread_link = syscallsNeedThreadLink(result.syscalls);
    return result;
}

void Codegen::collectSyscalls(const Program& program) {
    for (const Function& function : program.functions) {
        if (function.syscall) {
            syscalls_.insert(function.name);
        }
    }
}

void Codegen::emitSyscallLowering() {
    if (syscalls_.empty()) {
        return;
    }
    emitSyscallDefinitions(output_, syscalls_);
}

void Codegen::emitPrelude(const Program& program) {
    writeln("; generated by xlank");
    writeln("target triple = \"native\"");
    writeln("");

    for (const Function& function : program.functions) {
        if (function.external) {
            defined_functions_.insert(function.name);
        }
    }

    emitRuntimeDeclares(program);
}

void Codegen::emitRuntimeDeclares(const Program& program) {
    if (options_.runtime_exports.empty()) {
        return;
    }

    for (const FunctionSignature& runtime_fn : options_.runtime_exports) {
        if (definesFunction(program, runtime_fn.name)) {
            continue;
        }
        emitDeclareFunction(runtime_fn);
    }
}

bool Codegen::definesFunction(const Program& program, const std::string& name) const {
    if (defined_functions_.find(name) != defined_functions_.end()) {
        return true;
    }
    for (const Function& function : program.functions) {
        if (function.name == name && !function.body.statements.empty()) {
            return true;
        }
    }
    return false;
}

void Codegen::emitGlobals(const Program& program) {
    for (const GlobalVar& global : program.globals) {
        if (global.external) {
            writeln(globalName(global.name) + " = external global i32");
            continue;
        }

        globals_.insert(global.name);
        const std::string linkage = globalLinkage(global);
        if (global.init && global.init->kind == Expr::Kind::IntLiteral) {
            writeln(globalName(global.name) + " = " + linkage + "global i32 " +
                    std::to_string(global.init->int_value));
        } else {
            writeln(globalName(global.name) + " = " + linkage + "global i32 0");
        }
    }
    if (!program.globals.empty()) {
        writeln("");
    }
}

void Codegen::emitGlobalInit(const Program& program) {
    for (const GlobalVar& global : program.globals) {
        if (global.external) {
            continue;
        }
        if (!global.init || global.init->kind == Expr::Kind::IntLiteral) {
            continue;
        }
        needs_global_init_ = true;
        break;
    }
    if (!needs_global_init_) {
        return;
    }

    const std::string linkage = options_.build_kind == BuildKind::Lib ? "internal " : "";
    writeln("define " + linkage + "void @__xlang_init_globals() {");
    std::unordered_map<std::string, std::string> locals;
    for (const GlobalVar& global : program.globals) {
        if (global.external || !global.init || global.init->kind == Expr::Kind::IntLiteral) {
            continue;
        }
        const auto [ty, val] = emitExpr(*global.init, locals);
        writeln("  store " + ty + " " + val + ", i32* " + globalName(global.name) + ", align 4");
    }
    writeln("  ret void");
    writeln("}");
    writeln("");
}

void Codegen::emitDeclareFunction(const FunctionSignature& function) {
    std::ostringstream params;
    for (std::size_t i = 0; i < function.params.size(); ++i) {
        if (i > 0) {
            params << ", ";
        }
        params << "i32";
    }
    writeln("declare i32 @" + function.name + "(" + params.str() + ")");
    writeln("");
}

void Codegen::emitDeclareFunction(const Function& function) {
    std::ostringstream params;
    for (std::size_t i = 0; i < function.params.size(); ++i) {
        if (i > 0) {
            params << ", ";
        }
        params << "i32";
    }
    writeln("declare i32 @" + function.name + "(" + params.str() + ")");
    writeln("");
}

void Codegen::emitFunction(const Function& function) {
    std::ostringstream params;
    for (std::size_t i = 0; i < function.params.size(); ++i) {
        if (i > 0) {
            params << ", ";
        }
        params << "i32 %" << function.params[i];
    }

    writeln("define " + fnLinkage(function) + "i32 @" + function.name + "(" + params.str() + ") {");

    std::unordered_map<std::string, std::string> locals;
    for (const std::string& param : function.params) {
        const std::string ptr = localPtr(param);
        writeln("  " + ptr + " = alloca i32, align 4");
        writeln("  store i32 %" + param + ", i32* " + ptr + ", align 4");
        locals[param] = ptr;
    }

    if (function.name == "main" && needs_global_init_) {
        writeln("  call void @__xlang_init_globals()");
    }

    bool has_return = false;
    for (const Stmt& stmt : function.body.statements) {
        if (emitStatement(stmt, locals)) {
            has_return = true;
            break;
        }
    }

    if (!has_return) {
        writeln("  ret i32 0");
    }

    writeln("}");
    writeln("");
}

std::string Codegen::fnLinkage(const Function& function) const {
    if (function.external) {
        return "";
    }
    if (!function.exported && options_.build_kind == BuildKind::Lib) {
        return "internal ";
    }
    return "";
}

std::string Codegen::globalLinkage(const GlobalVar& global) const {
    if (global.external) {
        return "";
    }
    if (!global.exported && options_.build_kind == BuildKind::Lib) {
        return "internal ";
    }
    return "";
}

bool Codegen::emitStatement(const Stmt& stmt, std::unordered_map<std::string, std::string>& locals) {
    switch (stmt.kind) {
        case Stmt::Kind::Local: {
            const auto [ty, val] = emitExpr(*stmt.expr, locals);
            const std::string ptr = localPtr(stmt.name);
            writeln("  " + ptr + " = alloca i32, align 4");
            writeln("  store " + ty + " " + val + ", i32* " + ptr + ", align 4");
            locals[stmt.name] = ptr;
            return false;
        }
        case Stmt::Kind::Assign: {
            const auto [ty, val] = emitExpr(*stmt.expr, locals);
            const std::string target = resolveVar(stmt.name, locals);
            writeln("  store " + ty + " " + val + ", i32* " + target + ", align 4");
            return false;
        }
        case Stmt::Kind::Return: {
            if (stmt.return_value) {
                const auto [ty, val] = emitExpr(*stmt.return_value, locals);
                writeln("  ret " + ty + " " + val);
            } else {
                writeln("  ret i32 0");
            }
            return true;
        }
        case Stmt::Kind::Expr: {
            const auto [_, val] = emitExpr(*stmt.expr, locals);
            writeln("  ; discard " + val);
            return false;
        }
    }
    return false;
}

std::pair<std::string, std::string> Codegen::emitExpr(
    const Expr& expr, const std::unordered_map<std::string, std::string>& locals) {
    switch (expr.kind) {
        case Expr::Kind::IntLiteral:
            return {"i32", std::to_string(expr.int_value)};
        case Expr::Kind::Variable: {
            const std::string target = resolveVar(expr.name, locals);
            const std::string tmp = freshTmp();
            writeln("  " + tmp + " = load i32, i32* " + target + ", align 4");
            return {"i32", tmp};
        }
        case Expr::Kind::FunctionRef: {
            const std::string tmp = freshTmp();
            writeln("  " + tmp + " = ptrtoint i32 (i32)* @" + expr.name + " to i64");
            return {"i64", tmp};
        }
        case Expr::Kind::Binary: {
            const auto [_, left] = emitExpr(*expr.left, locals);
            const auto [__, right] = emitExpr(*expr.right, locals);
            const std::string tmp = freshTmp();
            std::string op;
            switch (expr.bin_op) {
                case BinOp::Add: op = "add"; break;
                case BinOp::Sub: op = "sub"; break;
                case BinOp::Mul: op = "mul"; break;
                case BinOp::Div: op = "sdiv"; break;
            }
            writeln("  " + tmp + " = " + op + " i32 " + left + ", " + right);
            return {"i32", tmp};
        }
        case Expr::Kind::Call: {
            std::ostringstream args;
            for (std::size_t i = 0; i < expr.args.size(); ++i) {
                if (i > 0) {
                    args << ", ";
                }
                const auto [ty, val] = emitExpr(*expr.args[i], locals);
                args << ty << " " << val;
            }
            const std::string tmp = freshTmp();
            writeln("  " + tmp + " = call i32 @" + expr.name + "(" + args.str() + ")");
            return {"i32", tmp};
        }
    }
    throw XlangError("invalid expression");
}

std::string Codegen::resolveVar(const std::string& name,
                                const std::unordered_map<std::string, std::string>& locals) const {
    const auto it = locals.find(name);
    if (it != locals.end()) {
        return it->second;
    }
    if (globals_.find(name) != globals_.end()) {
        return globalName(name);
    }
    throw XlangError("undefined variable `" + name + "`");
}

std::string Codegen::freshTmp() {
    return "%t" + std::to_string(tmp_counter_++);
}

std::string Codegen::localPtr(const std::string& name) {
    return "%" + name + ".addr";
}

std::string Codegen::globalName(const std::string& name) {
    return "@g_" + name;
}

void Codegen::writeln(const std::string& line) {
    output_ += line;
    output_ += '\n';
}

}  // namespace xlang
